CREATE TABLE [dbo].[Job]
(
	[Id] INT NOT NULL PRIMARY KEY Identity(1,1),
	[Title] nvarchar(max),
	[Description] nvarchar(max),
	[CustomerId] int,
	[CustomerName] nvarchar(max),
	[CustomerEmail] nvarchar(max),
	[CustomerAddress] nvarchar(max),
	[Latitude] decimal,
	[Longitutde] decimal,
	[CategoryId] int,
	[CategoryName] nvarchar(max),
	[ControlCenterId] int,
	[ControlCenterName] nvarchar(max),
	[AudioUrl] nvarchar(max),
	[ImageUrl] nvarchar(max),
	[VideoUrl] nvarchar(max),
	[Status] int,
	[CreatedAt] datetime,
	[CreatedBy] varchar(max),
	[UpdatedAt] datetime,
	[UpdateBy] varchar(max),
	[Date] datetime, 
	[IsAdded] bit not null default(0),
    CONSTRAINT [FK_Job_Category] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[Category]([Id]), 
    CONSTRAINT [FK_Job_ControlCenter] FOREIGN KEY ([ControlCenterId]) REFERENCES [dbo].[ControlCenter]([Id]), 
    CONSTRAINT [FK_Job_Customer] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customer]([Id]),

)
